### ISSUE TITLE
SQLite: unexpected db schema created

### ISSUE THREAD

**Issue by insanebaba** [prisma/migrate#196]
When I'm creating migrations for my model(_schema.prisma)_ :

```
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  enabled  = true
}

model User {
  id        Int      @id
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  posts     Post[]
  profile   Profile?
}
```

I get this sql as the migration script 
```
CREATE TABLE "lift"."User" (
  "createdAt" DATE NOT NULL DEFAULT '1970-01-01 00:00:00'  ,
  "email" TEXT NOT NULL DEFAULT ''  ,
  "id" INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT ,
  "name" TEXT    ,
  "role" TEXT NOT NULL DEFAULT 'USER'  
);
```
Here, _lift_ schema is created in my database which is unexpected. Is there a way to avoid this, or configure it?

**Comment by janpio** [comment]
Thanks @insanebaba, this is actually a real bug in our code that should be fixed then.

**Comment by mavilein** [comment]
I am not sure that this is a thing that we should fix as this only affects the `README`. This occurs only on SQLite because the driver requires you to attach files you want to use like this: `ATTACH [/path/to/file] AS [schema]`. In our case we hardcode the schema name to be always `lift`. It is a completely transient thing that is only used internally. It would require really awkward hacks to work around this.

**Comment by matthewmueller** [comment]
internal note: Dropping for this sprint. Bring it up in a later sprint.

**Comment by pantharshit00** [comment]
`"quaint"` prefix is used in the latest version instead of `"lift"` but yeah this still exists:
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/22195362/82868554-70f93d00-9f4a-11ea-967d-e2cced1fa80f.png">

Version: `@prisma/cli          : 2.0.0-alpha.1244`

**Comment by Jolg42** [comment]
This was fixed in CLI here https://github.com/prisma/prisma/blob/02725ac57787a26ec0f12445fd4e061f3adf833a/src/packages/migrate/src/utils/printDatabaseSteps.ts#L54
