### ISSUE TITLE
prisma2 migrate causes SIGSEGV segfault

### ISSUE THREAD

**Issue by sw-yx** [prisma/migrate#364]
i was going thru the redwood tutorial today and ran into this

repo: https://github.com/sw-yx/plsdelete-redwoodtest
redwood slack convo: https://redwoodjs.slack.com/archives/CE52EHRGX/p1583861333251000?thread_ts=1583858511.207700&cid=CE52EHRGX

```
git clean -dfx
yarn
yarn rw db up
```

and this is what happened

```bash
 ✘  redwoodblog   master ●  yarn rw db up 
yarn run v1.19.2
$ /Users/swyx/Work/testbeds/redwoodblog/node_modules/.bin/rw db up
Migrate database up... [started]
Error: Get config Error: Command was killed with SIGSEGV (Segmentation fault): /Users/swyx/Work/testbeds/redwoodblog/node_modules/prisma2/query-engine-darwin cli --get_config /private/var/folders/r7/x4h9vkx94tz1dw96tn1lfs9h0000gn/T/efdb9944-a3b7-456f-9603-5ba9f548dbfc
Migrate database up... [failed]
→ Command failed with exit code 1: prisma2 migrate up --experimental --create-db
Command failed with exit code 1: prisma2 migrate up --experimental --create-db
Generating the Prisma client... [started]
```

not sure whats wrong but @janpio asked me to make an issue.

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 112.20 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 71.0
    Firefox Nightly: 73.0a1
    Safari: 13.0.5
  npmGlobalPackages:
    npm: 6.13.4
```

**Comment by nikolasburk** [comment]
Hey Shawn 👋 nice to see you here! I tried to reproduce this on my machine based on the instructions you provided. This is the exact sequence of commands I ran:

```
git clone git@github.com:sw-yx/plsdelete-redwoodtest.git
cd plsdelete-redwoodtest/
git clean -dfx
yarn
yarn rw db up
```

I saw the following output:

~~~
$ yarn
                                       yarn rw db up
yarn install v1.22.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "@redwoodjs/core > @testing-library/react@9.5.0" has unmet peer dependency "react@*".
warning "@redwoodjs/core > @testing-library/react@9.5.0" has unmet peer dependency "react-dom@*".
[5/5] 🔨  Building fresh packages...
✨  Done in 14.48s.
yarn run v1.22.0
$ /Users/nikolasburk/Desktop/plsdelete-redwoodtest/node_modules/.bin/rw db up
Migrate database up... [started]
🏋️‍  migrate up

Datamodel that will initialize the db:

datasource DS {
  provider = "sqlite"
  url = "***"
}

generator photonjs {
  provider = "prisma-client-js"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}

model Post {
  id        Int @id @default(autoincrement())
  title     String
  body      String
  createdAt DateTime @default(now())
}

Checking the datasource for potential data loss...

Database Changes:

Migration                     Database actions                        Status

20200310123523-create-posts   1 CreateTable statements.               Done 🚀  
20200310132345-nouserexample  1 DropTable, 1 CreateTable statements.  Done 🚀  

You can get the detailed db changes with prisma2 migrate up --experimental --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md

🚀    Done with 2 migrations in 181ms.

Migrate database up... [completed]
Generating the Prisma client... [started]
✔ Generated Prisma Client to ./../node_modules/@prisma/client in 92ms

You can now start using Prisma Client in your code:

```
import { PrismaClient } from '@prisma/client'
// or const { PrismaClient } = require('@prisma/client')

const prisma = new PrismaClient()
```      

Explore the full API: http://pris.ly/d/client

Generating the Prisma client... [completed]
✨  Done in 2.62s.
~~~

**Comment by janpio** [comment]
Same on trying a reproduction on Windows.

Any more information available?
Could other colleagues reproduce your experience?

**Comment by janpio** [comment]
A similar issue, that we could reproduce, is tracked here: https://github.com/prisma/prisma2/issues/1819 It will probably also solve this problem here.

**Comment by janpio** [comment]
Hey @swyx, can you still reproduce the problem with the segfault? If so, could you zip up the whole project and send it over to piotrowski@prisma.io?

We currently can reproduce this ourselves consistently, but have a theory that the binary might have been corrupted somehow. Having the actual file would allow us to check that.

Also, there might a crash report on your machine. You can get to it by opening `console.app` (via Spotlight) and then going to the `User Reports` tab:
![image](https://user-images.githubusercontent.com/183673/76522381-d15a0180-6466-11ea-8172-526f2b3362c1.png)
(German screenshot unfortunately) If you have something in there for `query-engine-darwin`, it might be interesting for us to know what it says <3

**Comment by janpio** [comment]
Thanks for sending in the file. I posted a response with a workaround over here that might also apply to you: https://github.com/redwoodjs/redwood/issues/215#issuecomment-598465312

**Comment by sw-yx** [comment]
i'm going to close this now - glad you could repro
